DATASET: 
  NAME: ad2k
  DIR: /data/CH/data/ADEChallengeData2016
  IGNOREIDX: 255

MODEL:
  NUM_CLASSES: 150
  MODEL_NAME: vgg_voc_fcn
  BACKBONE: VGG
  HEAD: fcnhead
  INCHANNEL: [256, 512, 512]
  SCALES: [4, 8, 16]
  BN_MOMENTUM: 0.9
  MODE: bilinear
  BN_EPSILON: 1.0000001e-5
  BN_INIT_GAMMA: 0.0
  USE_DROPOUT: False
  DROPOUT_RATE: 0.5 #if dropout layer

TRAIN:
  DATA_TYPE: train
  BATCH_SIZE: 12
  SHUFFLE: True
  DROPOUT_RATE: 1.0
  EVAL_PERIOD: 1000
  CROP_SIZE: 480 # 112
  
TEST:
  DATA_TYPE: val
  BATCH_SIZE: 32
  CROP_SIZE: 224
  SHUFFLE: False

SOLVER:
  # 'step', 'steps_with_lrs', 'steps_with_relative_lrs', 'steps_with_decay, 'fixed''
  OPTIM: 'Adam'
  LR_POLICY: 'fixed' 
  BASE_LR: 0.0001
  MAX_ITER: 20000 # 50000
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BN: 0.0
  MOMENTUM: 0.9
  NESTEROV: True
  SCALE_MOMENTUM: True

  WARMUP:
    WARMUP_ON: False
    WARMUP_START_LR: 0.001
    WARMUP_END_ITER: 2000

NONLOCAL:
  USE_BN: True
  USE_SOFTMAX: False