DATASET: 
  NAME: voc
  DIR: /home/amax/data/PASCAL
  IGNOREIDX: 21

MODEL:
  NUM_CLASSES: 21
  MODEL_NAME: resnet18_voc_fcn
  BACKBONE: resnet18
  HEAD: fcn16s
  INCHANNEL: [64, 64, 128, 256, 512] #[4, 8, 16, 32, 64]
  SCALES: [1, 1, 1, 16, 2] # 
  BN_MOMENTUM: 0.9
  MODE: bilinear
  BN_EPSILON: 1.0000001e-5
  BN_INIT_GAMMA: 0.0
  USE_DROPOUT: False
  DROPOUT_RATE: 0.5 #if dropout layer
  NONLOCAL:
    USE: False
    DIM:  2 # 1D,2D,3D version
    TYPE: DotProduct # DotProduct,LocalGaussian,LocalConcatenation,EmbeddedGaussian
    USE_BN: True
    USE_SOFTMAX: False

TRAIN:
  DATA_TYPE: train
  BATCH_SIZE: 12
  SHUFFLE: True
  EVAL_PERIOD: 1000
  CROP_SIZE: 320 # 112
  
TEST:
  DATA_TYPE: val
  BATCH_SIZE: 32
  CROP_SIZE: 224
  SHUFFLE: False

SOLVER:
  # 'step', 'steps_with_lrs', 'steps_with_relative_lrs', 'steps_with_decay, 'fixed''
  OPTIM: 'Adam'
  LR_POLICY: 'fixed' 
  BASE_LR: 0.0001
  STEP_SIZES: [150000, 100000, 50000]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_ITER: 50000 # 50000 
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BN: 0.0
  MOMENTUM: 0.9
  NESTEROV: True
  SCALE_MOMENTUM: True

  WARMUP:
    WARMUP_ON: False
    WARMUP_START_LR: 0.001
    WARMUP_EPOCH: 5

CHECKPOINT:
  CHECKPOINT_MODEL: False
