DATASET: 
  NAME: voc
  DIR: /data/CH/data/PASCAL
  IGNOREIDX: 21
MODEL:
  NUM_CLASSES: 21
  MODEL_NAME: vgg_voc_fcn16s_nobn_scratch
  BACKBONE: VGG
  HEAD: fcn16s
  INCHANNEL: [64, 128, 256, 512, 512]
  SCALES: [1, 2, 4, 16, 2] # upscale factor for each featuremap
  FACTOR: 32 # upscale factor for each featuremap
  USE_BN: False
  PRETRAIN: False
  BN_MOMENTUM: 0.9
  MODE: bilinear
  BN_EPSILON: 1.0000001e-5
  BN_INIT_GAMMA: 0.0
  USE_DROPOUT: False
  DROPOUT_RATE: 0.5 #if dropout layer

TRAIN:
  DATA_TYPE: train
  BATCH_SIZE: 12
  SHUFFLE: True
  DROPOUT_RATE: 1.0
  EVAL_PERIOD: 1000
  CROP_SIZE: 320 # 112
  LODEMEMORY: False
TEST:
  DATA_TYPE: val
  BATCH_SIZE: 1
  CROP_SIZE: 224
  SHUFFLE: False
  LODEMEMORY: False

SOLVER:
  # 'step', 'steps_with_lrs', 'steps_with_relative_lrs', 'steps_with_decay, 'fixed''
  OPTIM: 'Adam'
  LR_POLICY: 'fixed' 
  BASE_LR: 0.1
  MAX_ITER: 50000 # 50000
  WEIGHT_DECAY: 0.001
  WEIGHT_DECAY_BN: 0.0
  MOMENTUM: 0.9
  NESTEROV: True
  SCALE_MOMENTUM: True

  WARMUP:
    WARMUP_ON: False
    WARMUP_START_LR: 0.0001
    WARMUP_EPOCH: 5

TENSORBOARD:
  HIST: False

CHECKPOINT:
  CHECKPOINT_MODEL: False

NONLOCAL:
  USE_BN: True
  USE_SOFTMAX: False